[platformio]
src_dir = ./

[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube

board_build.stm32cube.custom_config_header = yes

build_flags =
    -I Core/Inc
    -I Core/Inc/trng
    -I include

build_src_filter =
    +<src/>
    +<Core/Src/>
    +<Core/Inc/>